spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5440/appconfradb
    username: sicoob
    password: sicoobapi

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: jM+zON+rwRL8KV63UOB3+pJOEw8O2/SamvujhimQtWRhW1kqoq37fKu4QXcE5leKLUUk+7UmPSAIW30QIOg5ktkmCYg1s/wh0SNr7FV+sle40ql6H2xnR+NgaX+T15a61cBAgNK9Pgtly2fuy/XYwmUIB/Zur86Lo+V03z2FMxCtcbDJEovW2sWaEVoKXz5GOonvvFRvv73NGmO43uDRYgJx5Mbb2Q/8c5+ayyiDtYje+2hBOZFbwkxvQJocbERN9W9LwfBd+G+VbqBCFx9TybuGJQ272Z2STgNKvwDiQPLTqH2eAX6xKysawTMuHvpDLBhITKnUROWfYixjMT/MFX1VfZWZeBygDImnY0ykxoPFUsQe3wtweWmpa+j2rN/p9KySzu5/iZdcuLVz0iYu1OAnmpfiULYn3Q3pPaMG0VeApI+0hxFnVxB+kUAI4Y1WLUVCuLEESCPP9caAFYEG1sN1NBPZ50EwA9Q+oZiYn+83p53uey1GLFaLWKM2A5VSiUBJWADW8anqz5o8Ov5n9p/7YywdLiL2J5W7KJy7RvkF06igRIvpvWTlUc8DriO3ZuAstpM8x1Ch+CD3a6zlUN1HGw+Y6dM1fVJ890+9bC8mUTCGYgR3OmbSwU61e/99R/xIjqt2v2fiKyKVoUnCqlSSwIyFTa8e5A6dCQPIUUc=
      expiration: 900000
      refresh-token:
        expiration: 900000